In [1]:
import torch
import importlib

In [2]:
import pytorch_ssim
pytorch_ssim = importlib.reload(pytorch_ssim)

In [3]:
import ms_ssim_baseline

In [4]:
from PIL import Image
import numpy as np

In [5]:
img1 = Image.open('/Users/shenberg/Downloads/ronny_psycheledic.jpg')
i1 = np.array(img1)[None, ...]

In [6]:
i1.shape

(1, 934, 1400, 3)

In [7]:
i2 = i1*0.875 + 0.125*np.random.uniform(0,255,i1.shape)

In [8]:
ms_ssim_baseline.MultiScaleSSIM(i1, i2)

[ 0.54662894  0.83758567  0.95898881  0.98758793  0.99166316]
[ 0.5136332   0.78563175  0.90415816  0.94226102  0.96212063]


0.90633922236205355

In [9]:
ms_ssim_baseline.MultiScaleSSIM(i1/255, i2/255, max_val=1.)

[ 0.54662894  0.83758567  0.95898881  0.98758793  0.99166316]
[ 0.5136332   0.78563175  0.90415816  0.94226102  0.96212063]


0.90633922236205244

In [10]:
o = torch.ones(2,1)
z = torch.zeros(2,1)
(torch.cat([o+o,z,z,o+o],dim=1)**torch.Tensor([2,1,1,3])).prod(dim=1)


 0
 0
[torch.FloatTensor of size 2]

In [15]:
msssim = pytorch_ssim.MS_SSIM(max_val=255)

In [12]:
pi1 = torch.Tensor(i1)
pi2 = torch.Tensor(i2)

pi1 = pi1.permute(0,3,1,2)
pi2 = pi2.permute(0,3,1,2)

In [16]:
msssim(torch.autograd.Variable(pi1), torch.autograd.Variable(pi2))

[Variable containing:
 0.5466
[torch.FloatTensor of size 1]
, Variable containing:
 0.8376
[torch.FloatTensor of size 1]
, Variable containing:
 0.9590
[torch.FloatTensor of size 1]
, Variable containing:
 0.9876
[torch.FloatTensor of size 1]
, Variable containing:
 0.9917
[torch.FloatTensor of size 1]
]
Variable containing:
 0.9631
[torch.FloatTensor of size 1]



Variable containing:
 0.9065
[torch.FloatTensor of size 1]

In [14]:
torch.stack([torch.ones(2), torch.zeros(2)], dim=1)


 1  0
 1  0
[torch.FloatTensor of size 2x2]